services:
  - type: web
    name: pawns-gambit-cms
    env: node
    plan: free
    buildCommand: cd pawns-gambit-cms && npm install && npm run build
    startCommand: npm run dev
    rootDir: pawns-gambit-cms
    envVars:
      - key: NODE_ENV
        value: production
      # Add your environment variables here, e.g.:
      # - key: DATABASE_URL
      #   value: <your-database-url>
